server:
  port: 7788

rpc:
  url: http://main.confluxrpc.org

database:
  enabled: true
  host: 127.0.0.1:3306
  username: conflux_neurahive
  password: conflux_neurahive
  database: conflux_neurahive
  connMaxLifeTime: 3m
  maxOpenConns: 10
  maxIdleConns: 10

log:
  # Available levels are `trace`, `debug`, `info`, `error` and `fatal`
  level: info
  forceColor: false
