server:
  port: 7788

# Core space SDK client configurations
cfx:
  # Fullnode HTTP endpoint
  http: http://main.confluxrpc.com
  # Retry times if failure, if 0 never
  retry: 0
  # Interval duration before each retry
  retryInterval: 1s
  # Request timeout duration
  requestTimeout: 3s
  # Max connections allowed per fullnode
  maxConnsPerHost: 1024

# MySQL database configurations
database:
  enabled: true
  host: 127.0.0.1:3306
  username: conflux_neurahive
  password: conflux_neurahive
  database: conflux_neurahive
  connMaxLifeTime: 3m
  maxOpenConns: 10
  maxIdleConns: 10

# Logs configurations
log:
  # Available levels are `trace`, `debug`, `info`, `error` and `fatal`
  level: info
  forceColor: false
